server:
  port: 8189
  servlet:
    context-path: /security
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javalearnsecuriry?serverTimezone=UTC
    username: mysql
    password: mysql
#    data-username: mysql
#    data-password: mysql
#    schema-username: mysql
#    schema-password: mysql